### ISSUE TITLE
Constantly getting - ERR value is not an integer

### ISSUE THREAD

**Issue by thebravoman** [tyrauber/email_engine#6]
Sending one email and going to http://localhost:3000/messages/admin/emails

This is in the error log. Load More button does not work. Not sure why.
````
Redis::CommandError - ERR value is not an integer or out of range:
  redis (4.0.1) lib/redis/client.rb:119:in `call'
  redis (4.0.1) lib/redis.rb:1880:in `block in zrevrangebyscore'
  redis (4.0.1) lib/redis.rb:45:in `block in synchronize'
  /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  redis (4.0.1) lib/redis.rb:45:in `synchronize'
  redis (4.0.1) lib/redis.rb:1879:in `zrevrangebyscore'
  /home/kireto/robopartans/reduco/email_engine/app/models/email_engine/email.rb:111:in `all'
  /home/kireto/robopartans/reduco/email_engine/app/controllers/email_engine/emails_controller.rb:32:in `index'
````

**Comment by thebravoman** [comment]
The request send is

````
Started GET "/messages/admin/emails.json?type=sent&last=hour&interval=minute&limit=30&offset=0" for 127.0.0.1 at 2017-10-10 10:01:44 +0300
Processing by EmailEngine::EmailsController#index as JSON
  Parameters: {"type"=>"sent", "last"=>"hour", "interval"=>"minute", "limit"=>"30", "offset"=>"0"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 639ms (ActiveRecord: 0.4ms)

````

**Comment by thebravoman** [comment]
Got it. This happens when there is a single mail send.

The first time we enter into the loop below we get the response with one email. But then the loop continues and the second time we enter it gives an error.

````
 while
          p "zrevrangebyscore #{table_name('search')} #{opts[:finish]||"+inf"} #{opts[:start]||"-inf"} COUNT #{opts[:offset]||0} #{opts[:limit]||30} withscores"
          method = (opts[:order] == 'desc' ? :zrevrangebyscore : :zrangebyscore)
          byebug
          keys = EmailEngine.redis.send(method, "#{table_name('search')}", (opts[:finish]||"+inf"), (opts[:start]||"-inf"), limit: [opts[:offset], opts[:limit]], withscores: true).to_h.values
          records = keys.empty? ? [] : EmailEngine.redis.hmget(table_name, keys.map(&:to_i))
          records.compact.each do |record| 
            response.push filter_response(record, opts)
          end
          response.compact!
          opts[:offset] += opts[:limit]
          break if response.length >= opts[:limit].to_i || records.length == 0
        end
````

To fix it we must say
opts[:offset].to_i when calling EmailEngine. I am not sure about the implications of this to_i conversion and whether ti should be done on opts[:limit] also. Need you input here @tyrauber 

The successful call is

````
EmailEngine.redis.send(method, "#{table_name('search')}", (opts[:finish]||"+inf"), (opts[:start]||"-inf"), limit: [opts[:offset].to_i, opts[:limit]], withscores: true).to_h.values 

````

**Comment by thebravoman** [comment]
Commit is in https://github.com/thebravoman/email_engine/commit/ae8843486e5512c9bb87a02fac388144c1e7bf22

Should I create a pull request from this. Is there something I am missing?
